### ISSUE TITLE
[Bug] Webview2 rendering bugged out when open the menu panel

### ISSUE THREAD

**Issue by thedemons** [Exafunction/CodeiumVisualStudio#10]
When opening the menu panel, the chat messages will have some weird rendering issue. Resizing the window fixes this, it might be related to the fact that the webview2 is not recognized as a window to visual studio. It doesn't receive the "render" command, something like WM_PAINT, and bugs out.

https://github.com/Exafunction/CodeiumVisualStudio/assets/17585270/ef2d7460-6c37-48cf-8dd1-207dfdf090fb

**Comment by thedemons** [comment]
Somehow, I'm longer having this issue, I was having this from the beginning and it just magically disappears now

**Comment by fortenforge** [comment]
Seemingly fixed by #16
