### ISSUE TITLE
Error when using "Generate Commit Message" with package.json changes

### ISSUE THREAD

**Issue by edicarloslds** [Exafunction/CodeiumVisualStudio#109]
I'm encountering an issue when trying to use the "Generate Commit Message" feature. The following error message is displayed:

`Unable to generate commit message: ConnectError: [unknown] file is generated: content not valid for parsing`

<img width="460" alt="image" src="https://github.com/user-attachments/assets/e43eba48-c4c6-4576-b114-0265bdc428ec">

I noticed that this error only occurs when there are changes in the `package.json` and `package-lock.json` files.

**Steps to Reproduce:**

1. Make changes to the package.json and package-lock.json files.
2. Attempt to use the "Generate Commit Message" feature.

**Expected Behavior:**

The commit message should be generated without any errors.

**Actual Behavior:**

The error message mentioned above is displayed, and no commit message is generated.

**Environment:**

- Visual Studio Code version: 1.92.1 (Universal)
- Codeium extension version: 1.10.8
- OS: macOS Sonoma 14.6.1 (23G93)

**Comment by fortenforge** [comment]
This feature is in beta; you'll see improvements over the next few weeks. This repo is for the Codeium Visual Studio extension, not the VSCode extension. Issues with that extension should be reported in our Discord.
