### ISSUE TITLE
Hide chat window on startup

### ISSUE THREAD

**Issue by fortenforge** [Exafunction/CodeiumVisualStudio#27]
I'm seeing this warning about chat performance a lot

<img width="1289" alt="image" src="https://github.com/Exafunction/CodeiumVisualStudio/assets/7545794/57651e5d-ae3d-49f9-a6bc-b030ced0b602">

The warning allows the user to hide the chat window on startup. Ideally we'd be able to do that from the extension itself so the user doesn't see this warning. I looked into this earlier but couldn't figure out how to do it.

**Comment by thedemons** [comment]
I don't think we could do that, as it's the users' choice to do so, FYI this message only shows up in the debug build and when the debugger is attached, it's still annoying though.

Also, the `SetChatThemeAsync` function is bugging out here, I've had that a couple of times, and I'm not sure whether the function was never called or the javascript was injected too late.
