### ISSUE TITLE
[Enhancement] Better handling for the Language Server process

### ISSUE THREAD

**Issue by thedemons** [Exafunction/CodeiumVisualStudio#3]
The current state of the extension doesn't:
- Make the Language Server process exit when Visual Studio closes unexpectedly
- Restart the Language Server if it crashes
- Reconnect to the Web Chat Server if it disconnected

**Comment by fortenforge** [comment]
Point 2 is already handled actually. The process spawned is actually a manager process which in turn spawns the real language server process and monitors if it ever crashes and relaunches it if so.

**Comment by fortenforge** [comment]
Closed by #16
