### ISSUE TITLE
Syntax Error When Compile This Project

### ISSUE THREAD

**Issue by GongXunSS** [Exafunction/CodeiumVisualStudio#33]
Build started...
1>------ Build started: Project: CodeiumVS, Configuration: Release Any CPU ------
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\InlineDiff\InlineDiffAdornment.cs(268,36,268,37): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\LanguageServer\LanguageServer.cs(462,58,462,59): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\InlineDiff\InlineDiffView.cs(211,68,211,69): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\LanguageServer\LanguageServer.cs(462,59,462,60): error CS0443: Syntax error; value expected
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\InlineDiff\InlineDiffAdornment.cs(526,57,526,58): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Proposal\CodeiumProposalSource.cs(165,36,165,37): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Proposal\Mapper.cs(17,48,17,48): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Utilities\CodeAnalyzer.cs(15,74,15,75): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Utilities\CodeAnalyzer.cs(15,75,15,76): error CS0443: Syntax error; value expected
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Proposal\Mapper.cs(76,106,76,106): error CS0443: Syntax error; value expected
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Windows\RefactorCodeDialogWindow.cs(75,63,75,63): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Utilities\CodeAnalyzer.cs(126,28,126,29): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Windows\RefactorCodeDialogWindow.cs(91,110,91,111): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Windows\RefactorCodeDialogWindow.cs(100,110,100,110): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Windows\RefactorCodeDialogWindow.cs(103,132,103,132): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\Windows\RefactorCodeDialogWindow.cs(107,111,107,111): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\CodeiumVSPackage.cs(124,54,124,55): error CS1525: Invalid expression term '['
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\CodeiumVSPackage.cs(129,135,129,135): error CS0443: Syntax error; value expected
1>F:\3rdApps\Code\CodeiumVisualStudio\CodeiumVS\CodeiumVSPackage.cs(197,36,197,37): error CS1525: Invalid expression term '['
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 10:25 PM and took 01.680 seconds ==========

**Comment by thedemons** [comment]
Hey, can you open **Visual Studio Installer** and make sure **.NET 8.0 Runtime** is installed?
![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/17585270/229d9428-6339-4932-83c7-5791a6db6b5f)

**Comment by GongXunSS** [comment]
Thank you @thedemons.  I upgraded Visual Studio and now the compile is ok.
