### ISSUE TITLE
No autocomplete, codebase context, or codeblocks

### ISSUE THREAD

**Issue by MichaelBalkos** [Exafunction/CodeiumVisualStudio#35]
On Visual Studio 2022 I get the following issues:

1. When typing '@' and selecting Functions or Classes in the Codeium Chat, I get the error:

"No results for "". Please ensure that the relevant file is in your workspace and consider opening the file or neighboring files to make sure that it is indexed."

The Repos list is populated and works.

2. Autocomplete never appears. I cannot get the autocomplete to show me anything. 

I have tried the VSCode extension and it works there but on VS2022 I cant get it working. I've restarted, started a new project, opened all files in the project, etc. Nothing works.

The only thing that does work is when I highlight code and use the context menu options to refactor, explain, unit tests, etc. Then it can locate the code and use it as context.

**Comment by thedemons** [comment]
Hello, please make sure that Intellicode is enabled in the Options

![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/17585270/fc7d0938-eeff-4528-9c70-31224bbe3cca)

If it's already enabled, can you check if it logs "RequestProposalsAsync ..." in the output window when you type?

![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/17585270/b0f6e920-3525-4461-996f-fc81a8c7236b)

**Comment by MichaelBalkos** [comment]
Intellicode was enabled, not sure what happened but I tried again today and everything is working now. I didn't change anything.
Thanks for the quick reply.
