### ISSUE TITLE
Shortcuts not working on Mac

### ISSUE THREAD

**Issue by eddiemcconkie** [Exafunction/CodeiumVisualStudio#55]
A couple of the shortcuts don't seem to be working on Mac:
`Opt + C` (cancelCodeiumCommand) does not dismiss suggestions
`Opt + N` (diffActionReject) does not undo diffs

**Comment by fortenforge** [comment]
This is the repository for the Visual Studio extension—it looks like you're talking about vscode. Please make an issue on our Discord instead.
