### ISSUE TITLE
Cant select suggested code using tab in Visual Stuidio 2022 most of the time.

### ISSUE THREAD

**Issue by ranasrule** [Exafunction/CodeiumVisualStudio#64]
I cant select the suggested code by Codeium using the tab key in Visual Studio 2022 most of the time. I have Jetbrains Resharper installed and the project is in Visual Basic. Codeium shows suggestions but only around half the time does pressing the tab key select the suggestion.

**Comment by GTechMicah** [comment]
I had a very similar issue with Devexpress's CodeRush in visual studio 2022, one of coderush's shortcuts (specifically the tab to next reference) was overriding Codeium's tab autocomplete shortcut most of the time.


I had to disable the tab to next reference feature for coderush (I also disabled devexpress's Intellirush). So now Codeium's autocomplete works properly. 
It would be nice if there was a way around these types of conflicts (like have a setting in codeium to choose the autocomplete key).

**Comment by ranasrule** [comment]
> I had a very similar issue with Devexpress's CodeRush in visual studio 2022, one of coderush's shortcuts (specifically the tab to next reference) was overriding Codeium's tab autocomplete shortcut most of the time.
> 
> I had to disable the tab to next reference feature for coderush (I also disabled devexpress's Intellirush). So now Codeium's autocomplete works properly. It would be nice if there was a way around these types of conflicts (like have a setting in codeium to choose the autocomplete key).

I agree.... a setting in codeium to choose the autocomplete key would be awesome. Hope the devs consider this.

**Comment by SnakeInventor** [comment]
same issue

**Comment by fortenforge** [comment]
You can now rebind Codeium.CompleteSuggestion in the Visual Studio keybinding options to whatever you'd like.

**Comment by GTechMicah** [comment]
Awesome, Thank You @fortenforge !
