### ISSUE TITLE
[Security] Certificate for signing language server is outdated

### ISSUE THREAD

**Issue by M0n7y5** [Exafunction/CodeiumVisualStudio#69]
![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/17201053/e68d2ca1-d83b-4ea3-b684-3f8d242efef5)

Even tho its still valid today, VS is complaining about that.

![devenv_2dUkQaqKvI](https://github.com/Exafunction/CodeiumVisualStudio/assets/17201053/4c9aa9db-961e-4061-8f78-c8e342347284)

**Comment by mkozlina** [comment]
+1. I am having the same problem.

**Comment by shushu789** [comment]
+1

**Comment by Roofikk** [comment]
+1
![devenv_QkYRFahI2j](https://github.com/Exafunction/CodeiumVisualStudio/assets/56911734/6bdee1ad-20ef-4d27-8ba6-d97560844ec7)

**Comment by Roofikk** [comment]
I was helped by a complete restoration of Visual Studio via Visual Studio Installer

**Comment by M0n7y5** [comment]
> I was helped by a complete restoration of Visual Studio via Visual Studio Installer

This is not an Visual Studio problem. We just need to wait for dev team to re-sign the lang server with new certificate.

**Comment by fortenforge** [comment]
Working on this right now.

**Comment by fortenforge** [comment]
Just published 1.8.23 for VS, should be fixed there; please upgrade.

**Comment by Roofikk** [comment]
It looks working so far. Good job!

**Comment by fortenforge** [comment]
did you update to 1.8.23
