### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by dasiniwoyebushuo** [Exafunction/CodeiumVisualStudio#76]
what?
![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/103472526/62fc3b0d-88f6-439f-9fb4-a14dfc119acb)

**Comment by tiagobbadoco** [comment]
I'm having the same problem on Visual Studio Comunity 2022 17.9.6

**Comment by rebizu** [comment]
I have the same error in my vs pro 2022 17.9.6 
![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/1035736/4ca13e6a-fd34-45ce-8343-c5bd92cddf61)

Maby this can help implementing the codelens better 
https://www.codingwithcalvin.net/extending-visual-studio-codelens-functionality/

**Comment by BachiMjavanadze** [comment]
the same problem

![codeium-over](https://github.com/Exafunction/CodeiumVisualStudio/assets/38082501/9589d832-ef2f-41bf-9ad7-f43b334b990a)

**Comment by raphaelquati** [comment]
Same here. 
VS2022 17.10.0 Preview 2.0
Codeium 1.8.25

![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/815086/87a3b7c5-cfb0-4abf-a508-35aefae50796)

**Comment by fortenforge** [comment]
Fixed in 1.8.27
