### ISSUE TITLE
Hide "Refactor | Explain" over every method

### ISSUE THREAD

**Issue by DottorPagliaccius** [Exafunction/CodeiumVisualStudio#78]
Hi, Codeium is putting a very annoyng "Codeium Refactor | Explain" menu over every method, class, etc, there's a way to hide it?

![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/7924114/1143fb75-0c4e-41bf-9c28-733b3b6cb894)

**Comment by DottorPagliaccius** [comment]
Uhm suddendly it's gone. My magic powers, I suppose. Closing.

**Comment by DottorPagliaccius** [comment]
Forget it, it's back

**Comment by Jaytheway** [comment]
Found a way to disable (version 1.8.27): go to Tools->Options->Text Editor->CodeLens and uncheck 'Show CodeiumCodeLens'.
![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/22476284/9ec5f351-1127-4649-b933-9ae8c9f2a710)

..or you can right click on any Codeium CodeLens and go directly to CodeLens options:
![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/22476284/67638fc1-7f90-4c25-9cb0-6f9137244588)
