### ISSUE TITLE
重叠了vs2022中的提示

### ISSUE THREAD

**Issue by lianyitj** [Exafunction/CodeiumVisualStudio#79]
<img width="281" alt="image" src="https://github.com/Exafunction/CodeiumVisualStudio/assets/10227648/df3c9cee-d25d-4a75-ab05-351c5ebad5e5">

**Comment by fortenforge** [comment]
Try 1.8.26

**Comment by lianyitj** [comment]
> 试用 1.8.26

All right, thank you!
