### ISSUE TITLE
Code hints overlapping 

### ISSUE THREAD

**Issue by fredericoregateiro** [Exafunction/CodeiumVisualStudio#81]
In the class definitions and on public methods the codeium hints are overlapping vs code hints

![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/6304701/1bbac6d4-c56f-4ee5-ba5d-45bd7e61e4a2)

and 
![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/6304701/2880e300-1171-4e5a-81d1-9d0001f6242b)

If the code contains attributes, it's ok

![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/6304701/df467fb5-003b-428a-ae86-19430eae4c54)

**Comment by fortenforge** [comment]
Try 1.8.26
