### ISSUE TITLE
The line Codeium: Refactor | Explain is so annoying in Visual Studio 2022

### ISSUE THREAD

**Issue by trungkien2003ntk** [Exafunction/CodeiumVisualStudio#83]
I'm currently using Visual Studio 2022 17.8.1 with Codeium 1.8.25.

- The issue that I encountered was the text "Codeium: Refactor | Explain" above a C# class/interface is conflicting with Visual Studio's Codelens. It makes the text  "x references" overlap with the text "Codeium: Refactor | Explain" which make me struggle to click them.
- Also, whenever I type a character in the c# class/interface code, the text  "Codeium: Refactor | Explain" disappear and appear again after stopped typing. Because of that, the class's code is moving up/down as the line disappear/appear. It looks like the code is shaking around and I'm going crazy with that.
- I can't find any settings to turn off that line. I'm looking forward to seeing the fix soon.

**Comment by fortenforge** [comment]
Try 1.8.26
